# Generated by Django 5.0.2 on 2024-03-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsandloans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='customer_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='savingsitem',
            name='customer_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='savingsitem',
            name='payment_ref',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
