# Generated by Django 5.0.2 on 2024-03-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsandloans', '0002_savings_customer_id_savingsitem_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_ref',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
