# Generated by Django 5.0.2 on 2024-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsandloans', '0003_loan_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
